<<<<<<< HEAD
# Generated by Django 4.0.10 on 2023-10-25 16:56
=======
# Generated by Django 4.2.5 on 2023-10-25 16:49
>>>>>>> 8dccc0201e0767527da208fb961d089aa52dbb57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
    ]
