<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-27 14:34

=======
# Generated by Django 4.2.5 on 2023-10-25 16:49
>>>>>>> 4bc6aa999fbb830f45a74f278988d2ac66ddaab7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
    ]
